### PR TITLE
Add a new LVM scenario with a thin pool

### PR DESCRIPTION
**Pull request by imobachgs**
Unfortunatelly, [bsc#1086661](https://bugzilla.suse.com/show_bug.cgi?id=1086661) will cause the test to fail.

### CODE REVIEW

**Comment by schubi2** [comment]
I would insert this nice test also into:
https://github.com/yast/aytests-tests/blob/master/jenkins_tests
in order to run it on jenkins too.

**Review by schubi2 — CHANGES_REQUESTED** [review]
.

**Comment by imobachgs** [comment]
Oh, you are right. Thanks!

**Comment by imobachgs** [comment]
I've rebased the PR. @schubi2 please, could you have another look? Thanks!

**Comment by schubi2** [comment]
Hm, somehow I still not see any changes in the jenkins_test file. Or have I missed something ?

**Comment by imobachgs** [comment]
Oh, you are right. Perhaps I messed it up when rebasing my changes. Fixed now.

**Review by schubi2 — APPROVED** [review]
LGTM

**Pull request merged**
