### PR TITLE
Auto partition

### PR DESCRIPTION
**Pull request by imobachgs**

### CODE REVIEW

**Comment by schubi2** [comment]
LGTM

**Review by jreidinger — APPROVED** [review]
already aproved by schubi

**Comment by imobachgs** [comment]
As the test was quite outdated, I've rebase it on `SLE-12-SP2` branch. Please, review.

**Comment by imobachgs** [comment]
Rebased again on `SLE-12-SP2`.

**Comment by teclator** [comment]
LGTM, at least the updated part ;)

**Comment by imobachgs** [comment]
Outdated.

**Pull request closed without merging**
