### PR TITLE
Improve http verification script

### PR DESCRIPTION
**Pull request by rwx788**
As we got two copies of same script, we need to sync them at some point.
If we have same script, it can be removed from openQA distri repo. Our
aim is to have only a single copy of profiles and verification scripts.
This version of script is more readable and matches http profile we use
in openQA, which is also sligthly different to the one in aytests
package. 
TBD how to proceed.

### CODE REVIEW

**Comment by mvidner** [comment]
So this script is a duplicate of a master copy that lives elsewhere? Then I'd expect a fat warning in a comment in its header, with a Git URL link to the master.

Also, if we really must embed Perl in Bash, then I'd prefer to use a quoted heredoc, `<<'EOP'`, so that the backslashes can be avoided.

**Comment by rwx788** [comment]
We plan to have everything in one place, which is this [repo](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/data/autoyast_sle12sp2/http.sh). But our test will fail with current script in aytests. We also need to be sure that it won't break integration tests, as expected open ports are different...

**Comment by rwx788** [comment]
And thanks for hint about heredoc, I was not aware that we can avoid this pain with backslashes.

**Comment by rwx788** [comment]
As per discussion with schubi2, I'll create branch in original repo and create PR from there, so it's easier to verify that these changes haven't broken anything.

**Pull request closed without merging**
