### PR TITLE
Invalid languages check (bsc#991001)

### PR DESCRIPTION
**Pull request by imobachgs**
Check that invalid languages are handled properly, as requested in [bsc#991001](https://bugzilla.suse.com/show_bug.cgi?id=991001). This test should not be merged until SLE 12 SP2 contains [the fix](https://github.com/yast/yast-country/pull/79).

### CODE REVIEW

**Comment by kobliha** [comment]
LGTM

The code is, indeed, not yet merged into SP2

**Comment by kobliha** [comment]
@imobachgs Let's merge, the fix is already in and we can't know when it will be accepted into the build

**Comment by imobachgs** [comment]
@kobliha Anyway, AutoYaST integration tests will download the latest version from our repositories, so it should be ok.

**Comment by imobachgs** [comment]
Thanks.

**Pull request merged**
